<?php

/**
 * @file
 * Contains address_migration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function address_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the address_migration module.
    case 'help.page.address_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a migration path from addressfield or location module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function address_migration_theme() {
  $theme = [];

  return $theme;
}
