<?php

/**
 * @file
 * Provides migrate related hooks.
 */

use Drupal\migrate\Entity\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\node\Plugin\migrate\source\d6\Node;

/**
 * Implement hook_migrate_prepare_row.
 *
 * @param \Drupal\migrate\Row $row
 * @param \Drupal\migrate\Plugin\MigrateSourceInterface $source
 * @param \Drupal\migrate\Entity\MigrationInterface $migration
 */
function address_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($source instanceof Node) {
    $query = $source->getDatabase()->select('location', 'l');
    $query->innerJoin('location_instance', 'li', 'li.lid = l.lid');
    $query->condition('li.vid', $row->getSourceProperty('vid'));
    $query->fields('l');
    $query->addField('li', 'vid');
    $locations = $query->execute()->fetchAllAssoc('lid', PDO::FETCH_ASSOC);
    if (!empty($locations)) {
      $debug = 1;
    }
    $row->setSourceProperty('address_migrate_data', $locations);
  }
}
